PageSource:  Page Source
ChangeDescription:  Description of Change
NeedChangeDescription:  Description of Change cannot be empty.
View: view
Edit: edit
History: history
Discuss: discuss
FrontPage: Front page
Directory: Directory
Categories: Categories
RandomPage: Random page
RecentActivity: Recent activity
UploadFile: Upload a file
AtomFeed:  Atom feed
Help: Help
Search: Search
Go: Go
RawPageSource:  Raw page source
PrintableVersion: Printable version
DeleteThisPage: Delete this page
ConfirmDelete page@Page: Are you sure you want to delete #{page}?
Delete: Delete
Deleted page@Page: Deleted #{page}
Reverted rev@RevisionId: Reverted to #{rev}
Merged rev@RevisionId: The page has been edited since you checked it out. Changes from revision #{rev} have been merged into your edits below.

