PageSource:  Page Source
ChangeDescription:  Description of Change
NeedChangeDescription:  Description of Change cannot be empty.
View: View latest
Page: Page
Edit: Edit
History: History
Discuss: Discuss
FrontPage: Front page
Directory: Directory
Categories: Categories
Category: Category
RandomPage: Random page
RecentActivity: Recent activity
UploadFile: Upload a file
AtomFeed:  Atom feed
Help: Help
Search: Search
Go: Go
Export: Export
RawPageSource:  Raw page source
PrintableVersion: Printable version
DeleteThisPage: Delete this page
ConfirmDelete page@Page: Are you sure you want to delete #{page}?
Delete: Delete
Deleted page@Page: Deleted #{page}
Reverted rev@RevisionId: Reverted to #{rev}
Merged rev@RevisionId: The page has been edited since you checked it out. Changes from revision #{rev} have been merged into your edits below.
NewPage page@Page:  There is no page #{page}.  Create it by editing below.
DragDiff: Drag one revision onto another to see differences.
SiteFeedTitle:  Recent changes to the wiki.
PageFeedTitle page@Page:  Recent changes to #{page}.
FileToUpload: File to upload
WikiName: Name in wiki
Overwrite: Overwrite existing file
InvalidPageName: Invalid page name
FileExists: A file by that name exists in the wiki -- check Overwrite to overwrite
FileUnchanged: The file matches the version already in the repository.

